name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:
  build_samd:

    name: build samd

    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - Seeeduino:samd:seeed_XIAO_m0

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1
  
    - name: Install core
      run: |
        arduino-cli core update-index --additional-urls https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
        arduino-cli core install Seeeduino:samd@1.8.5 --additional-urls https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
  
    - name: Install libraries
      run: |
        arduino-cli lib install "Adafruit GFX Library@1.10.10"
        arduino-cli lib install "Adafruit SSD1306@2.4.5"
        arduino-cli lib install "Adafruit BusIO@1.14.1"
  
    - name: Install Custom Libraries
      run: |
        mkdir -p ~/Arduino/libraries
   
        git clone --depth 1 https://github.com/marcel-licence/ML_SynthTools.git \
          ~/Arduino/libraries/ML_SynthTools
   
        git clone --depth 1 https://github.com/marcel-licence/ML_SynthTools_Lib.git \
          ~/Arduino/libraries/ML_SynthTools_Lib

    - name: Compile sketch
      run: |
        arduino-cli compile \
          --fqbn Seeeduino:samd:seeed_XIAO_m0 \
          --output-dir build \
          ./ 
  
    - name: Generate UF2
      if: always()
      run: |
        BIN_FILE=$(find build -name "*.bin" | head -n 1)
        
        # Download both the script AND the required families definition
        curl -L https://raw.githubusercontent.com/microsoft/uf2/master/utils/uf2conv.py -o uf2conv.py
        curl -L https://raw.githubusercontent.com/microsoft/uf2/master/utils/uf2families.json -o uf2families.json
    
        python3 uf2conv.py "$BIN_FILE" \
          --family SAMD21 \
          --convert \
          --output build/firmware.uf2
  
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware-xiao_samd21
        path: build/*

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/*.bin
          build/*.hex
          build/*.elf
          build/*.map
          build/*.uf2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}