name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_samd:

    name: build samd

    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - Seeeduino:samd:seeed_XIAO_m0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: Seeeduino:samd
              source-url: https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json              
              version: 1.8.5
          sketch-paths: |
            - ./
          libraries: |
              - source-url: https://github.com/marcel-licence/ML_SynthTools.git
                name: ML_SynthTools


